package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AppointmentServic generated by hbm2java
 */
@Entity
@Table(name = "appointment_servic", catalog = "pet_clinic1")
public class AppointmentServic implements java.io.Serializable {

	private AppointmentServicId id;
	private Appointment appointment;
	private Servic servic;

	public AppointmentServic() {
	}

	public AppointmentServic(AppointmentServicId id, Appointment appointment, Servic servic) {
		this.id = id;
		this.appointment = appointment;
		this.servic = servic;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "servicId", column = @Column(name = "servic_id", nullable = false)),
			@AttributeOverride(name = "appointmentId", column = @Column(name = "appointment_id", nullable = false)) })
	public AppointmentServicId getId() {
		return this.id;
	}

	public void setId(AppointmentServicId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "appointment_id", nullable = false, insertable = false, updatable = false)
	public Appointment getAppointment() {
		return this.appointment;
	}

	public void setAppointment(Appointment appointment) {
		this.appointment = appointment;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "servic_id", nullable = false, insertable = false, updatable = false)
	public Servic getServic() {
		return this.servic;
	}

	public void setServic(Servic servic) {
		this.servic = servic;
	}

}
