package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DoctorServicId generated by hbm2java
 */
@Embeddable
public class DoctorServicId implements java.io.Serializable {

	private int servicTypeId;
	private int doctorId;

	public DoctorServicId() {
	}

	public DoctorServicId(int servicTypeId, int doctorId) {
		this.servicTypeId = servicTypeId;
		this.doctorId = doctorId;
	}

	@Column(name = "servic_type_id", nullable = false)
	public int getServicTypeId() {
		return this.servicTypeId;
	}

	public void setServicTypeId(int servicTypeId) {
		this.servicTypeId = servicTypeId;
	}

	@Column(name = "doctor_id", nullable = false)
	public int getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DoctorServicId))
			return false;
		DoctorServicId castOther = (DoctorServicId) other;

		return (this.getServicTypeId() == castOther.getServicTypeId())
				&& (this.getDoctorId() == castOther.getDoctorId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getServicTypeId();
		result = 37 * result + this.getDoctorId();
		return result;
	}

}
