package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DoctorServic generated by hbm2java
 */
@Entity
@Table(name = "doctor_servic", catalog = "pet_clinic1")
public class DoctorServic implements java.io.Serializable {

	private DoctorServicId id;
	private Doctor doctor;
	private ServicType servicType;

	public DoctorServic() {
	}

	public DoctorServic(DoctorServicId id, Doctor doctor, ServicType servicType) {
		this.id = id;
		this.doctor = doctor;
		this.servicType = servicType;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "servicTypeId", column = @Column(name = "servic_type_id", nullable = false)),
			@AttributeOverride(name = "doctorId", column = @Column(name = "doctor_id", nullable = false)) })
	public DoctorServicId getId() {
		return this.id;
	}

	public void setId(DoctorServicId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctor_id", nullable = false, insertable = false, updatable = false)
	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "servic_type_id", nullable = false, insertable = false, updatable = false)
	public ServicType getServicType() {
		return this.servicType;
	}

	public void setServicType(ServicType servicType) {
		this.servicType = servicType;
	}

}
