package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ScheduleServicId generated by hbm2java
 */
@Embeddable
public class ScheduleServicId implements java.io.Serializable {

	private int servicTypeId;
	private int scheduleId;

	public ScheduleServicId() {
	}

	public ScheduleServicId(int servicTypeId, int scheduleId) {
		this.servicTypeId = servicTypeId;
		this.scheduleId = scheduleId;
	}

	@Column(name = "servic_type_id", nullable = false)
	public int getServicTypeId() {
		return this.servicTypeId;
	}

	public void setServicTypeId(int servicTypeId) {
		this.servicTypeId = servicTypeId;
	}

	@Column(name = "schedule_id", nullable = false)
	public int getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(int scheduleId) {
		this.scheduleId = scheduleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ScheduleServicId))
			return false;
		ScheduleServicId castOther = (ScheduleServicId) other;

		return (this.getServicTypeId() == castOther.getServicTypeId())
				&& (this.getScheduleId() == castOther.getScheduleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getServicTypeId();
		result = 37 * result + this.getScheduleId();
		return result;
	}

}
