package com.coder.model;
// Generated Jul 17, 2020 9:43:20 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Servic generated by hbm2java
 */
@Entity
@Table(name = "servic", catalog = "pet_clinic1")
public class Servic implements java.io.Serializable {

	private Integer servicId;
	private ServicType servicType;
	private String servicName;
	private int servicPoint;
	private int servicMinute;
	private String servicAbout;
	private Set<AppointmentServic> appointmentServics = new HashSet<AppointmentServic>(0);

	public Servic() {
	}

	public Servic(ServicType servicType, String servicName, int servicPoint, int servicMinute, String servicAbout) {
		this.servicType = servicType;
		this.servicName = servicName;
		this.servicPoint = servicPoint;
		this.servicMinute = servicMinute;
		this.servicAbout = servicAbout;
	}

	public Servic(ServicType servicType, String servicName, int servicPoint, int servicMinute, String servicAbout,
			Set<AppointmentServic> appointmentServics) {
		this.servicType = servicType;
		this.servicName = servicName;
		this.servicPoint = servicPoint;
		this.servicMinute = servicMinute;
		this.servicAbout = servicAbout;
		this.appointmentServics = appointmentServics;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "servic_id", unique = true, nullable = false)
	public Integer getServicId() {
		return this.servicId;
	}

	public void setServicId(Integer servicId) {
		this.servicId = servicId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "servic_type_id", nullable = false)
	public ServicType getServicType() {
		return this.servicType;
	}

	public void setServicType(ServicType servicType) {
		this.servicType = servicType;
	}

	@Column(name = "servic_name", nullable = false, length = 60)
	public String getServicName() {
		return this.servicName;
	}

	public void setServicName(String servicName) {
		this.servicName = servicName;
	}

	@Column(name = "servic_point", nullable = false)
	public int getServicPoint() {
		return this.servicPoint;
	}

	public void setServicPoint(int servicPoint) {
		this.servicPoint = servicPoint;
	}

	@Column(name = "servic_minute", nullable = false)
	public int getServicMinute() {
		return this.servicMinute;
	}

	public void setServicMinute(int servicMinute) {
		this.servicMinute = servicMinute;
	}

	@Column(name = "servic_about", nullable = false, length = 200)
	public String getServicAbout() {
		return this.servicAbout;
	}

	public void setServicAbout(String servicAbout) {
		this.servicAbout = servicAbout;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "servic")
	public Set<AppointmentServic> getAppointmentServics() {
		return this.appointmentServics;
	}

	public void setAppointmentServics(Set<AppointmentServic> appointmentServics) {
		this.appointmentServics = appointmentServics;
	}

}
